a=float(input("Enter first number:"))
b=float(input("Enter second number"))
sum=a+b
diff=a-b
multi=a*b
div=a/b
print("Sum=",sum)
print("Difference=",diff)
print("Multiplication=",multi)
print("Division=",div)
